/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fed' at '13.12.17 14:52' with Gradle 2.9
 *
 * @author fed, @date 13.12.17 14:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
